package org.simple4j.eventdistributor.beans;

public enum ErrorType
{
	PARAMETER_ERROR,EVENT_NOTFOUND,CALLER_NOTAUTHORIZED,EVENT_INPROGRESS,RUNTIME_ERROR,DUPLICATE_REQUEST,PUBLISH_ATTEMPT_NOTFOUND, EVENT_ALREADY_PROCESSED
}
